basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.pause(500)
    basic.showIcon(IconNames.Skull)
    basic.pause(500)
    basic.showIcon(IconNames.House)
    basic.pause(500)
    basic.showIcon(IconNames.StickFigure)
    basic.pause(500)
})
